package com.kshl.huihuimall.base.dal.mapper;

import com.kshl.huihuimall.base.dal.entity.CategoryThree;
import com.kshl.huihuimall.base.dal.entity.CategoryThreeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoryThreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_three
     *
     * @mbg.generated
     */
    long countByExample(CategoryThreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_three
     *
     * @mbg.generated
     */
    int deleteByExample(CategoryThreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_three
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_three
     *
     * @mbg.generated
     */
    int insert(CategoryThree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_three
     *
     * @mbg.generated
     */
    int insertSelective(CategoryThree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_three
     *
     * @mbg.generated
     */
    List<CategoryThree> selectByExample(CategoryThreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_three
     *
     * @mbg.generated
     */
    CategoryThree selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_three
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CategoryThree record, @Param("example") CategoryThreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_three
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CategoryThree record, @Param("example") CategoryThreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_three
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CategoryThree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_three
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CategoryThree record);
}