package com.kshl.huihuimall.base.dal.mapper;

import com.kshl.huihuimall.base.dal.entity.InventoryToProduct;
import com.kshl.huihuimall.base.dal.entity.InventoryToProductExample;
import java.util.List;

import com.kshl.huihuimall.console.base.dto.Stock;
import org.apache.ibatis.annotations.Param;

public interface InventoryToProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_to_product
     *
     * @mbg.generated
     */
    long countByExample(InventoryToProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_to_product
     *
     * @mbg.generated
     */
    int deleteByExample(InventoryToProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_to_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_to_product
     *
     * @mbg.generated
     */
    int insert(InventoryToProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_to_product
     *
     * @mbg.generated
     */
    int insertSelective(InventoryToProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_to_product
     *
     * @mbg.generated
     */
    List<InventoryToProduct> selectByExample(InventoryToProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_to_product
     *
     * @mbg.generated
     */
    InventoryToProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_to_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InventoryToProduct record, @Param("example") InventoryToProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_to_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InventoryToProduct record, @Param("example") InventoryToProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_to_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InventoryToProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_to_product
     *
     * @mbg.generated
     */

}