package com.kshl.huihuimall.base.dal.mapper;

import com.kshl.huihuimall.base.dal.entity.InventoryOut;
import com.kshl.huihuimall.base.dal.entity.InventoryOutExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InventoryOutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_out
     *
     * @mbg.generated
     */
    long countByExample(InventoryOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_out
     *
     * @mbg.generated
     */
    int deleteByExample(InventoryOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_out
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_out
     *
     * @mbg.generated
     */
    int insert(InventoryOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_out
     *
     * @mbg.generated
     */
    int insertSelective(InventoryOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_out
     *
     * @mbg.generated
     */
    List<InventoryOut> selectByExample(InventoryOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_out
     *
     * @mbg.generated
     */
    InventoryOut selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_out
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InventoryOut record, @Param("example") InventoryOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_out
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InventoryOut record, @Param("example") InventoryOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_out
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InventoryOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_out
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InventoryOut record);
}