package com.kshl.huihuimall.base.dal.mapper;

import com.kshl.huihuimall.base.dal.entity.KsAccount;
import com.kshl.huihuimall.base.dal.entity.KsAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KsAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_account
     *
     * @mbg.generated
     */
    long countByExample(KsAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_account
     *
     * @mbg.generated
     */
    int deleteByExample(KsAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_account
     *
     * @mbg.generated
     */
    int insert(KsAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_account
     *
     * @mbg.generated
     */
    int insertSelective(KsAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_account
     *
     * @mbg.generated
     */
    List<KsAccount> selectByExample(KsAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_account
     *
     * @mbg.generated
     */
    KsAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_account
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") KsAccount record, @Param("example") KsAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_account
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") KsAccount record, @Param("example") KsAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KsAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KsAccount record);
}