package com.kshl.huihuimall.base.dal.mapper;

import com.kshl.huihuimall.base.dal.entity.KsAccountToRole;
import com.kshl.huihuimall.base.dal.entity.KsAccountToRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KsAccountToRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_account_to_role
     *
     * @mbg.generated
     */
    long countByExample(KsAccountToRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_account_to_role
     *
     * @mbg.generated
     */
    int deleteByExample(KsAccountToRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_account_to_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_account_to_role
     *
     * @mbg.generated
     */
    int insert(KsAccountToRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_account_to_role
     *
     * @mbg.generated
     */
    int insertSelective(KsAccountToRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_account_to_role
     *
     * @mbg.generated
     */
    List<KsAccountToRole> selectByExample(KsAccountToRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_account_to_role
     *
     * @mbg.generated
     */
    KsAccountToRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_account_to_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") KsAccountToRole record, @Param("example") KsAccountToRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_account_to_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") KsAccountToRole record, @Param("example") KsAccountToRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_account_to_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KsAccountToRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_account_to_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KsAccountToRole record);
}