package com.kshl.huihuimall.base.dal.mapper;

import com.kshl.huihuimall.base.dal.entity.ProfitRecord;
import com.kshl.huihuimall.base.dal.entity.ProfitRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProfitRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit_record
     *
     * @mbg.generated
     */
    long countByExample(ProfitRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit_record
     *
     * @mbg.generated
     */
    int deleteByExample(ProfitRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit_record
     *
     * @mbg.generated
     */
    int insert(ProfitRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit_record
     *
     * @mbg.generated
     */
    int insertSelective(ProfitRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit_record
     *
     * @mbg.generated
     */
    List<ProfitRecord> selectByExample(ProfitRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit_record
     *
     * @mbg.generated
     */
    ProfitRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProfitRecord record, @Param("example") ProfitRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProfitRecord record, @Param("example") ProfitRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProfitRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profit_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProfitRecord record);
}