package com.kshl.huihuimall.base.dal.mapper;

import com.kshl.huihuimall.base.dal.entity.ReturnExchangeOrder;
import com.kshl.huihuimall.base.dal.entity.ReturnExchangeOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReturnExchangeOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_exchange_order
     *
     * @mbg.generated
     */
    long countByExample(ReturnExchangeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_exchange_order
     *
     * @mbg.generated
     */
    int deleteByExample(ReturnExchangeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_exchange_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_exchange_order
     *
     * @mbg.generated
     */
    int insert(ReturnExchangeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_exchange_order
     *
     * @mbg.generated
     */
    int insertSelective(ReturnExchangeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_exchange_order
     *
     * @mbg.generated
     */
    List<ReturnExchangeOrder> selectByExample(ReturnExchangeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_exchange_order
     *
     * @mbg.generated
     */
    ReturnExchangeOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_exchange_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ReturnExchangeOrder record, @Param("example") ReturnExchangeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_exchange_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ReturnExchangeOrder record, @Param("example") ReturnExchangeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_exchange_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReturnExchangeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return_exchange_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReturnExchangeOrder record);
}