package com.kshl.huihuimall.base.dal.mapper;

import com.kshl.huihuimall.base.dal.entity.StoreOrder;
import com.kshl.huihuimall.base.dal.entity.StoreOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StoreOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_order
     *
     * @mbg.generated
     */
    long countByExample(StoreOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_order
     *
     * @mbg.generated
     */
    int deleteByExample(StoreOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_order
     *
     * @mbg.generated
     */
    int insert(StoreOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_order
     *
     * @mbg.generated
     */
    int insertSelective(StoreOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_order
     *
     * @mbg.generated
     */
    List<StoreOrder> selectByExample(StoreOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_order
     *
     * @mbg.generated
     */
    StoreOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StoreOrder record, @Param("example") StoreOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StoreOrder record, @Param("example") StoreOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StoreOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StoreOrder record);
}