package com.kshl.huihuimall.base.dal.mapper;

import com.kshl.huihuimall.base.dal.entity.StoreApply;
import com.kshl.huihuimall.base.dal.entity.StoreApplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StoreApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_apply
     *
     * @mbg.generated
     */
    long countByExample(StoreApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_apply
     *
     * @mbg.generated
     */
    int deleteByExample(StoreApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_apply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_apply
     *
     * @mbg.generated
     */
    int insert(StoreApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_apply
     *
     * @mbg.generated
     */
    int insertSelective(StoreApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_apply
     *
     * @mbg.generated
     */
    List<StoreApply> selectByExample(StoreApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_apply
     *
     * @mbg.generated
     */
    StoreApply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_apply
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StoreApply record, @Param("example") StoreApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_apply
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StoreApply record, @Param("example") StoreApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StoreApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StoreApply record);
}