package com.kshl.huihuimall.base.dal.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class FinancialConfigureExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    public FinancialConfigureExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStoreProfitIsNull() {
            addCriterion("store_profit is null");
            return (Criteria) this;
        }

        public Criteria andStoreProfitIsNotNull() {
            addCriterion("store_profit is not null");
            return (Criteria) this;
        }

        public Criteria andStoreProfitEqualTo(BigDecimal value) {
            addCriterion("store_profit =", value, "storeProfit");
            return (Criteria) this;
        }

        public Criteria andStoreProfitNotEqualTo(BigDecimal value) {
            addCriterion("store_profit <>", value, "storeProfit");
            return (Criteria) this;
        }

        public Criteria andStoreProfitGreaterThan(BigDecimal value) {
            addCriterion("store_profit >", value, "storeProfit");
            return (Criteria) this;
        }

        public Criteria andStoreProfitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("store_profit >=", value, "storeProfit");
            return (Criteria) this;
        }

        public Criteria andStoreProfitLessThan(BigDecimal value) {
            addCriterion("store_profit <", value, "storeProfit");
            return (Criteria) this;
        }

        public Criteria andStoreProfitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("store_profit <=", value, "storeProfit");
            return (Criteria) this;
        }

        public Criteria andStoreProfitIn(List<BigDecimal> values) {
            addCriterion("store_profit in", values, "storeProfit");
            return (Criteria) this;
        }

        public Criteria andStoreProfitNotIn(List<BigDecimal> values) {
            addCriterion("store_profit not in", values, "storeProfit");
            return (Criteria) this;
        }

        public Criteria andStoreProfitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("store_profit between", value1, value2, "storeProfit");
            return (Criteria) this;
        }

        public Criteria andStoreProfitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("store_profit not between", value1, value2, "storeProfit");
            return (Criteria) this;
        }

        public Criteria andRecommendProfitIsNull() {
            addCriterion("recommend_profit is null");
            return (Criteria) this;
        }

        public Criteria andRecommendProfitIsNotNull() {
            addCriterion("recommend_profit is not null");
            return (Criteria) this;
        }

        public Criteria andRecommendProfitEqualTo(BigDecimal value) {
            addCriterion("recommend_profit =", value, "recommendProfit");
            return (Criteria) this;
        }

        public Criteria andRecommendProfitNotEqualTo(BigDecimal value) {
            addCriterion("recommend_profit <>", value, "recommendProfit");
            return (Criteria) this;
        }

        public Criteria andRecommendProfitGreaterThan(BigDecimal value) {
            addCriterion("recommend_profit >", value, "recommendProfit");
            return (Criteria) this;
        }

        public Criteria andRecommendProfitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("recommend_profit >=", value, "recommendProfit");
            return (Criteria) this;
        }

        public Criteria andRecommendProfitLessThan(BigDecimal value) {
            addCriterion("recommend_profit <", value, "recommendProfit");
            return (Criteria) this;
        }

        public Criteria andRecommendProfitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("recommend_profit <=", value, "recommendProfit");
            return (Criteria) this;
        }

        public Criteria andRecommendProfitIn(List<BigDecimal> values) {
            addCriterion("recommend_profit in", values, "recommendProfit");
            return (Criteria) this;
        }

        public Criteria andRecommendProfitNotIn(List<BigDecimal> values) {
            addCriterion("recommend_profit not in", values, "recommendProfit");
            return (Criteria) this;
        }

        public Criteria andRecommendProfitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("recommend_profit between", value1, value2, "recommendProfit");
            return (Criteria) this;
        }

        public Criteria andRecommendProfitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("recommend_profit not between", value1, value2, "recommendProfit");
            return (Criteria) this;
        }

        public Criteria andConsumptionProfitIsNull() {
            addCriterion("consumption_profit is null");
            return (Criteria) this;
        }

        public Criteria andConsumptionProfitIsNotNull() {
            addCriterion("consumption_profit is not null");
            return (Criteria) this;
        }

        public Criteria andConsumptionProfitEqualTo(BigDecimal value) {
            addCriterion("consumption_profit =", value, "consumptionProfit");
            return (Criteria) this;
        }

        public Criteria andConsumptionProfitNotEqualTo(BigDecimal value) {
            addCriterion("consumption_profit <>", value, "consumptionProfit");
            return (Criteria) this;
        }

        public Criteria andConsumptionProfitGreaterThan(BigDecimal value) {
            addCriterion("consumption_profit >", value, "consumptionProfit");
            return (Criteria) this;
        }

        public Criteria andConsumptionProfitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("consumption_profit >=", value, "consumptionProfit");
            return (Criteria) this;
        }

        public Criteria andConsumptionProfitLessThan(BigDecimal value) {
            addCriterion("consumption_profit <", value, "consumptionProfit");
            return (Criteria) this;
        }

        public Criteria andConsumptionProfitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("consumption_profit <=", value, "consumptionProfit");
            return (Criteria) this;
        }

        public Criteria andConsumptionProfitIn(List<BigDecimal> values) {
            addCriterion("consumption_profit in", values, "consumptionProfit");
            return (Criteria) this;
        }

        public Criteria andConsumptionProfitNotIn(List<BigDecimal> values) {
            addCriterion("consumption_profit not in", values, "consumptionProfit");
            return (Criteria) this;
        }

        public Criteria andConsumptionProfitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("consumption_profit between", value1, value2, "consumptionProfit");
            return (Criteria) this;
        }

        public Criteria andConsumptionProfitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("consumption_profit not between", value1, value2, "consumptionProfit");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table financial_configure
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}