package com.kshl.huihuimall.base.dal.entity;

import java.io.Serializable;

public class Storehouse implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storehouse.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storehouse.storehouse_name
     *
     * @mbg.generated
     */
    private String storehouseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storehouse.area_id
     *
     * @mbg.generated
     */
    private Integer areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storehouse.area_name
     *
     * @mbg.generated
     */
    private String areaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storehouse.space
     *
     * @mbg.generated
     */
    private Double space;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storehouse.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storehouse.manager_id
     *
     * @mbg.generated
     */
    private Integer managerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table storehouse
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storehouse.id
     *
     * @return the value of storehouse.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storehouse.id
     *
     * @param id the value for storehouse.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storehouse.storehouse_name
     *
     * @return the value of storehouse.storehouse_name
     *
     * @mbg.generated
     */
    public String getStorehouseName() {
        return storehouseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storehouse.storehouse_name
     *
     * @param storehouseName the value for storehouse.storehouse_name
     *
     * @mbg.generated
     */
    public void setStorehouseName(String storehouseName) {
        this.storehouseName = storehouseName == null ? null : storehouseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storehouse.area_id
     *
     * @return the value of storehouse.area_id
     *
     * @mbg.generated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storehouse.area_id
     *
     * @param areaId the value for storehouse.area_id
     *
     * @mbg.generated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storehouse.area_name
     *
     * @return the value of storehouse.area_name
     *
     * @mbg.generated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storehouse.area_name
     *
     * @param areaName the value for storehouse.area_name
     *
     * @mbg.generated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storehouse.space
     *
     * @return the value of storehouse.space
     *
     * @mbg.generated
     */
    public Double getSpace() {
        return space;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storehouse.space
     *
     * @param space the value for storehouse.space
     *
     * @mbg.generated
     */
    public void setSpace(Double space) {
        this.space = space;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storehouse.address
     *
     * @return the value of storehouse.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storehouse.address
     *
     * @param address the value for storehouse.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storehouse.manager_id
     *
     * @return the value of storehouse.manager_id
     *
     * @mbg.generated
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storehouse.manager_id
     *
     * @param managerId the value for storehouse.manager_id
     *
     * @mbg.generated
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storehouse
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", storehouseName=").append(storehouseName);
        sb.append(", areaId=").append(areaId);
        sb.append(", areaName=").append(areaName);
        sb.append(", space=").append(space);
        sb.append(", address=").append(address);
        sb.append(", managerId=").append(managerId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}