package com.kshl.huihuimall.base.dal.mapper;

import com.kshl.huihuimall.base.dal.entity.CategoryTwo;
import com.kshl.huihuimall.base.dal.entity.CategoryTwoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoryTwoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_two
     *
     * @mbg.generated
     */
    long countByExample(CategoryTwoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_two
     *
     * @mbg.generated
     */
    int deleteByExample(CategoryTwoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_two
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_two
     *
     * @mbg.generated
     */
    int insert(CategoryTwo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_two
     *
     * @mbg.generated
     */
    int insertSelective(CategoryTwo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_two
     *
     * @mbg.generated
     */
    List<CategoryTwo> selectByExample(CategoryTwoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_two
     *
     * @mbg.generated
     */
    CategoryTwo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_two
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CategoryTwo record, @Param("example") CategoryTwoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_two
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CategoryTwo record, @Param("example") CategoryTwoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_two
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CategoryTwo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_two
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CategoryTwo record);
}