package com.kshl.huihuimall.base.dal.mapper;

import com.kshl.huihuimall.base.dal.entity.KsMenuResource;
import com.kshl.huihuimall.base.dal.entity.KsMenuResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KsMenuResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_menu_resource
     *
     * @mbg.generated
     */
    long countByExample(KsMenuResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_menu_resource
     *
     * @mbg.generated
     */
    int deleteByExample(KsMenuResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_menu_resource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_menu_resource
     *
     * @mbg.generated
     */
    int insert(KsMenuResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_menu_resource
     *
     * @mbg.generated
     */
    int insertSelective(KsMenuResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_menu_resource
     *
     * @mbg.generated
     */
    List<KsMenuResource> selectByExample(KsMenuResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_menu_resource
     *
     * @mbg.generated
     */
    KsMenuResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_menu_resource
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") KsMenuResource record, @Param("example") KsMenuResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_menu_resource
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") KsMenuResource record, @Param("example") KsMenuResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_menu_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KsMenuResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_menu_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KsMenuResource record);
}