package com.kshl.huihuimall.base.dal.mapper;

import com.kshl.huihuimall.base.dal.entity.Payinfo;
import com.kshl.huihuimall.base.dal.entity.PayinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PayinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payinfo
     *
     * @mbg.generated
     */
    long countByExample(PayinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payinfo
     *
     * @mbg.generated
     */
    int deleteByExample(PayinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payinfo
     *
     * @mbg.generated
     */
    int insert(Payinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payinfo
     *
     * @mbg.generated
     */
    int insertSelective(Payinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payinfo
     *
     * @mbg.generated
     */
    List<Payinfo> selectByExample(PayinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payinfo
     *
     * @mbg.generated
     */
    Payinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payinfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Payinfo record, @Param("example") PayinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payinfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Payinfo record, @Param("example") PayinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Payinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Payinfo record);
}