package com.kshl.huihuimall.base.dal.mapper;

import com.kshl.huihuimall.base.dal.entity.ProductReview;
import com.kshl.huihuimall.base.dal.entity.ProductReviewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductReviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_review
     *
     * @mbg.generated
     */
    long countByExample(ProductReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_review
     *
     * @mbg.generated
     */
    int deleteByExample(ProductReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_review
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_review
     *
     * @mbg.generated
     */
    int insert(ProductReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_review
     *
     * @mbg.generated
     */
    int insertSelective(ProductReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_review
     *
     * @mbg.generated
     */
    List<ProductReview> selectByExample(ProductReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_review
     *
     * @mbg.generated
     */
    ProductReview selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_review
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProductReview record, @Param("example") ProductReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_review
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProductReview record, @Param("example") ProductReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_review
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_review
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductReview record);
}