package com.kshl.huihuimall.base.dal.entity;

import java.io.Serializable;
import java.util.Date;

public class Customer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.store_id
     *
     * @mbg.generated
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.recommend_person_id
     *
     * @mbg.generated
     */
    private Integer recommendPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.phone_number
     *
     * @mbg.generated
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.open_id
     *
     * @mbg.generated
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.last_login
     *
     * @mbg.generated
     */
    private Date lastLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.identify_code
     *
     * @mbg.generated
     */
    private String identifyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.expiretime
     *
     * @mbg.generated
     */
    private Long expiretime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id
     *
     * @return the value of customer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id
     *
     * @param id the value for customer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.store_id
     *
     * @return the value of customer.store_id
     *
     * @mbg.generated
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.store_id
     *
     * @param storeId the value for customer.store_id
     *
     * @mbg.generated
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.recommend_person_id
     *
     * @return the value of customer.recommend_person_id
     *
     * @mbg.generated
     */
    public Integer getRecommendPersonId() {
        return recommendPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.recommend_person_id
     *
     * @param recommendPersonId the value for customer.recommend_person_id
     *
     * @mbg.generated
     */
    public void setRecommendPersonId(Integer recommendPersonId) {
        this.recommendPersonId = recommendPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.phone_number
     *
     * @return the value of customer.phone_number
     *
     * @mbg.generated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.phone_number
     *
     * @param phoneNumber the value for customer.phone_number
     *
     * @mbg.generated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.open_id
     *
     * @return the value of customer.open_id
     *
     * @mbg.generated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.open_id
     *
     * @param openId the value for customer.open_id
     *
     * @mbg.generated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.last_login
     *
     * @return the value of customer.last_login
     *
     * @mbg.generated
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.last_login
     *
     * @param lastLogin the value for customer.last_login
     *
     * @mbg.generated
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.identify_code
     *
     * @return the value of customer.identify_code
     *
     * @mbg.generated
     */
    public String getIdentifyCode() {
        return identifyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.identify_code
     *
     * @param identifyCode the value for customer.identify_code
     *
     * @mbg.generated
     */
    public void setIdentifyCode(String identifyCode) {
        this.identifyCode = identifyCode == null ? null : identifyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.expiretime
     *
     * @return the value of customer.expiretime
     *
     * @mbg.generated
     */
    public Long getExpiretime() {
        return expiretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.expiretime
     *
     * @param expiretime the value for customer.expiretime
     *
     * @mbg.generated
     */
    public void setExpiretime(Long expiretime) {
        this.expiretime = expiretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", storeId=").append(storeId);
        sb.append(", recommendPersonId=").append(recommendPersonId);
        sb.append(", phoneNumber=").append(phoneNumber);
        sb.append(", openId=").append(openId);
        sb.append(", lastLogin=").append(lastLogin);
        sb.append(", identifyCode=").append(identifyCode);
        sb.append(", expiretime=").append(expiretime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}