package com.kshl.huihuimall.base.dal.entity;

import java.io.Serializable;
import java.util.Date;

public class Device implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_code
     *
     * @mbg.generated
     */
    private String deviceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.store_id
     *
     * @mbg.generated
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.binding_status
     *
     * @mbg.generated
     */
    private Integer bindingStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.bing_time
     *
     * @mbg.generated
     */
    private Date bingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table device
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.id
     *
     * @return the value of device.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.id
     *
     * @param id the value for device.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_code
     *
     * @return the value of device.device_code
     *
     * @mbg.generated
     */
    public String getDeviceCode() {
        return deviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_code
     *
     * @param deviceCode the value for device.device_code
     *
     * @mbg.generated
     */
    public void setDeviceCode(String deviceCode) {
        this.deviceCode = deviceCode == null ? null : deviceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.store_id
     *
     * @return the value of device.store_id
     *
     * @mbg.generated
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.store_id
     *
     * @param storeId the value for device.store_id
     *
     * @mbg.generated
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.binding_status
     *
     * @return the value of device.binding_status
     *
     * @mbg.generated
     */
    public Integer getBindingStatus() {
        return bindingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.binding_status
     *
     * @param bindingStatus the value for device.binding_status
     *
     * @mbg.generated
     */
    public void setBindingStatus(Integer bindingStatus) {
        this.bindingStatus = bindingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.bing_time
     *
     * @return the value of device.bing_time
     *
     * @mbg.generated
     */
    public Date getBingTime() {
        return bingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.bing_time
     *
     * @param bingTime the value for device.bing_time
     *
     * @mbg.generated
     */
    public void setBingTime(Date bingTime) {
        this.bingTime = bingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", deviceCode=").append(deviceCode);
        sb.append(", storeId=").append(storeId);
        sb.append(", bindingStatus=").append(bindingStatus);
        sb.append(", bingTime=").append(bingTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}