package com.kshl.huihuimall.base.dal.entity;

import java.io.Serializable;
import java.util.Date;

public class InventoryRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_record.product_id
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_record.outstorehouse_id
     *
     * @mbg.generated
     */
    private Integer outstorehouseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_record.instorehouse_id
     *
     * @mbg.generated
     */
    private Integer instorehouseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_record.onhand
     *
     * @mbg.generated
     */
    private Integer onhand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_record.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_record.stock_status
     *
     * @mbg.generated
     */
    private Integer stockStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_record.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_record.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inventory_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_record.id
     *
     * @return the value of inventory_record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_record.id
     *
     * @param id the value for inventory_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_record.product_id
     *
     * @return the value of inventory_record.product_id
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_record.product_id
     *
     * @param productId the value for inventory_record.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_record.outstorehouse_id
     *
     * @return the value of inventory_record.outstorehouse_id
     *
     * @mbg.generated
     */
    public Integer getOutstorehouseId() {
        return outstorehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_record.outstorehouse_id
     *
     * @param outstorehouseId the value for inventory_record.outstorehouse_id
     *
     * @mbg.generated
     */
    public void setOutstorehouseId(Integer outstorehouseId) {
        this.outstorehouseId = outstorehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_record.instorehouse_id
     *
     * @return the value of inventory_record.instorehouse_id
     *
     * @mbg.generated
     */
    public Integer getInstorehouseId() {
        return instorehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_record.instorehouse_id
     *
     * @param instorehouseId the value for inventory_record.instorehouse_id
     *
     * @mbg.generated
     */
    public void setInstorehouseId(Integer instorehouseId) {
        this.instorehouseId = instorehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_record.onhand
     *
     * @return the value of inventory_record.onhand
     *
     * @mbg.generated
     */
    public Integer getOnhand() {
        return onhand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_record.onhand
     *
     * @param onhand the value for inventory_record.onhand
     *
     * @mbg.generated
     */
    public void setOnhand(Integer onhand) {
        this.onhand = onhand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_record.status
     *
     * @return the value of inventory_record.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_record.status
     *
     * @param status the value for inventory_record.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_record.stock_status
     *
     * @return the value of inventory_record.stock_status
     *
     * @mbg.generated
     */
    public Integer getStockStatus() {
        return stockStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_record.stock_status
     *
     * @param stockStatus the value for inventory_record.stock_status
     *
     * @mbg.generated
     */
    public void setStockStatus(Integer stockStatus) {
        this.stockStatus = stockStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_record.update_user
     *
     * @return the value of inventory_record.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_record.update_user
     *
     * @param updateUser the value for inventory_record.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_record.update_time
     *
     * @return the value of inventory_record.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_record.update_time
     *
     * @param updateTime the value for inventory_record.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_record
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", outstorehouseId=").append(outstorehouseId);
        sb.append(", instorehouseId=").append(instorehouseId);
        sb.append(", onhand=").append(onhand);
        sb.append(", status=").append(status);
        sb.append(", stockStatus=").append(stockStatus);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}