package com.kshl.huihuimall.base.dal.entity;

import java.io.Serializable;
import java.util.Date;

public class InventoryTransfer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_transfer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_transfer.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_transfer.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_transfer.outhouse_id
     *
     * @mbg.generated
     */
    private Integer outhouseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_transfer.inhouse_id
     *
     * @mbg.generated
     */
    private Integer inhouseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_transfer.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_transfer.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_transfer.instatus
     *
     * @mbg.generated
     */
    private String instatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory_transfer.outstatus
     *
     * @mbg.generated
     */
    private String outstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inventory_transfer
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_transfer.id
     *
     * @return the value of inventory_transfer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_transfer.id
     *
     * @param id the value for inventory_transfer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_transfer.code
     *
     * @return the value of inventory_transfer.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_transfer.code
     *
     * @param code the value for inventory_transfer.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_transfer.status
     *
     * @return the value of inventory_transfer.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_transfer.status
     *
     * @param status the value for inventory_transfer.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_transfer.outhouse_id
     *
     * @return the value of inventory_transfer.outhouse_id
     *
     * @mbg.generated
     */
    public Integer getOuthouseId() {
        return outhouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_transfer.outhouse_id
     *
     * @param outhouseId the value for inventory_transfer.outhouse_id
     *
     * @mbg.generated
     */
    public void setOuthouseId(Integer outhouseId) {
        this.outhouseId = outhouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_transfer.inhouse_id
     *
     * @return the value of inventory_transfer.inhouse_id
     *
     * @mbg.generated
     */
    public Integer getInhouseId() {
        return inhouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_transfer.inhouse_id
     *
     * @param inhouseId the value for inventory_transfer.inhouse_id
     *
     * @mbg.generated
     */
    public void setInhouseId(Integer inhouseId) {
        this.inhouseId = inhouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_transfer.create_time
     *
     * @return the value of inventory_transfer.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_transfer.create_time
     *
     * @param createTime the value for inventory_transfer.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_transfer.create_user
     *
     * @return the value of inventory_transfer.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_transfer.create_user
     *
     * @param createUser the value for inventory_transfer.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_transfer.instatus
     *
     * @return the value of inventory_transfer.instatus
     *
     * @mbg.generated
     */
    public String getInstatus() {
        return instatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_transfer.instatus
     *
     * @param instatus the value for inventory_transfer.instatus
     *
     * @mbg.generated
     */
    public void setInstatus(String instatus) {
        this.instatus = instatus == null ? null : instatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory_transfer.outstatus
     *
     * @return the value of inventory_transfer.outstatus
     *
     * @mbg.generated
     */
    public String getOutstatus() {
        return outstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory_transfer.outstatus
     *
     * @param outstatus the value for inventory_transfer.outstatus
     *
     * @mbg.generated
     */
    public void setOutstatus(String outstatus) {
        this.outstatus = outstatus == null ? null : outstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_transfer
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", status=").append(status);
        sb.append(", outhouseId=").append(outhouseId);
        sb.append(", inhouseId=").append(inhouseId);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", instatus=").append(instatus);
        sb.append(", outstatus=").append(outstatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}