package com.kshl.huihuimall.base.dal.entity;

import java.util.ArrayList;
import java.util.List;

public class ThiradAccountTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    public ThiradAccountTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andThiradAccountIsNull() {
            addCriterion("thirad_account is null");
            return (Criteria) this;
        }

        public Criteria andThiradAccountIsNotNull() {
            addCriterion("thirad_account is not null");
            return (Criteria) this;
        }

        public Criteria andThiradAccountEqualTo(Integer value) {
            addCriterion("thirad_account =", value, "thiradAccount");
            return (Criteria) this;
        }

        public Criteria andThiradAccountNotEqualTo(Integer value) {
            addCriterion("thirad_account <>", value, "thiradAccount");
            return (Criteria) this;
        }

        public Criteria andThiradAccountGreaterThan(Integer value) {
            addCriterion("thirad_account >", value, "thiradAccount");
            return (Criteria) this;
        }

        public Criteria andThiradAccountGreaterThanOrEqualTo(Integer value) {
            addCriterion("thirad_account >=", value, "thiradAccount");
            return (Criteria) this;
        }

        public Criteria andThiradAccountLessThan(Integer value) {
            addCriterion("thirad_account <", value, "thiradAccount");
            return (Criteria) this;
        }

        public Criteria andThiradAccountLessThanOrEqualTo(Integer value) {
            addCriterion("thirad_account <=", value, "thiradAccount");
            return (Criteria) this;
        }

        public Criteria andThiradAccountIn(List<Integer> values) {
            addCriterion("thirad_account in", values, "thiradAccount");
            return (Criteria) this;
        }

        public Criteria andThiradAccountNotIn(List<Integer> values) {
            addCriterion("thirad_account not in", values, "thiradAccount");
            return (Criteria) this;
        }

        public Criteria andThiradAccountBetween(Integer value1, Integer value2) {
            addCriterion("thirad_account between", value1, value2, "thiradAccount");
            return (Criteria) this;
        }

        public Criteria andThiradAccountNotBetween(Integer value1, Integer value2) {
            addCriterion("thirad_account not between", value1, value2, "thiradAccount");
            return (Criteria) this;
        }

        public Criteria andThiradNameIsNull() {
            addCriterion("thirad_name is null");
            return (Criteria) this;
        }

        public Criteria andThiradNameIsNotNull() {
            addCriterion("thirad_name is not null");
            return (Criteria) this;
        }

        public Criteria andThiradNameEqualTo(String value) {
            addCriterion("thirad_name =", value, "thiradName");
            return (Criteria) this;
        }

        public Criteria andThiradNameNotEqualTo(String value) {
            addCriterion("thirad_name <>", value, "thiradName");
            return (Criteria) this;
        }

        public Criteria andThiradNameGreaterThan(String value) {
            addCriterion("thirad_name >", value, "thiradName");
            return (Criteria) this;
        }

        public Criteria andThiradNameGreaterThanOrEqualTo(String value) {
            addCriterion("thirad_name >=", value, "thiradName");
            return (Criteria) this;
        }

        public Criteria andThiradNameLessThan(String value) {
            addCriterion("thirad_name <", value, "thiradName");
            return (Criteria) this;
        }

        public Criteria andThiradNameLessThanOrEqualTo(String value) {
            addCriterion("thirad_name <=", value, "thiradName");
            return (Criteria) this;
        }

        public Criteria andThiradNameLike(String value) {
            addCriterion("thirad_name like", value, "thiradName");
            return (Criteria) this;
        }

        public Criteria andThiradNameNotLike(String value) {
            addCriterion("thirad_name not like", value, "thiradName");
            return (Criteria) this;
        }

        public Criteria andThiradNameIn(List<String> values) {
            addCriterion("thirad_name in", values, "thiradName");
            return (Criteria) this;
        }

        public Criteria andThiradNameNotIn(List<String> values) {
            addCriterion("thirad_name not in", values, "thiradName");
            return (Criteria) this;
        }

        public Criteria andThiradNameBetween(String value1, String value2) {
            addCriterion("thirad_name between", value1, value2, "thiradName");
            return (Criteria) this;
        }

        public Criteria andThiradNameNotBetween(String value1, String value2) {
            addCriterion("thirad_name not between", value1, value2, "thiradName");
            return (Criteria) this;
        }

        public Criteria andThiradStateIsNull() {
            addCriterion("thirad_state is null");
            return (Criteria) this;
        }

        public Criteria andThiradStateIsNotNull() {
            addCriterion("thirad_state is not null");
            return (Criteria) this;
        }

        public Criteria andThiradStateEqualTo(Integer value) {
            addCriterion("thirad_state =", value, "thiradState");
            return (Criteria) this;
        }

        public Criteria andThiradStateNotEqualTo(Integer value) {
            addCriterion("thirad_state <>", value, "thiradState");
            return (Criteria) this;
        }

        public Criteria andThiradStateGreaterThan(Integer value) {
            addCriterion("thirad_state >", value, "thiradState");
            return (Criteria) this;
        }

        public Criteria andThiradStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("thirad_state >=", value, "thiradState");
            return (Criteria) this;
        }

        public Criteria andThiradStateLessThan(Integer value) {
            addCriterion("thirad_state <", value, "thiradState");
            return (Criteria) this;
        }

        public Criteria andThiradStateLessThanOrEqualTo(Integer value) {
            addCriterion("thirad_state <=", value, "thiradState");
            return (Criteria) this;
        }

        public Criteria andThiradStateIn(List<Integer> values) {
            addCriterion("thirad_state in", values, "thiradState");
            return (Criteria) this;
        }

        public Criteria andThiradStateNotIn(List<Integer> values) {
            addCriterion("thirad_state not in", values, "thiradState");
            return (Criteria) this;
        }

        public Criteria andThiradStateBetween(Integer value1, Integer value2) {
            addCriterion("thirad_state between", value1, value2, "thiradState");
            return (Criteria) this;
        }

        public Criteria andThiradStateNotBetween(Integer value1, Integer value2) {
            addCriterion("thirad_state not between", value1, value2, "thiradState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table thirad_account_type
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}