package com.kshl.huihuimall.console.controller.product.request;

import java.math.BigDecimal;
import java.util.Date;
public class newProductRequest  {
        private Integer id;
        private Integer shelvesStatus;
        private Date offshelvesDate;
        private Date shelvesDate;
        private Integer categoryoneId;
        private Integer categorytwoId;
        private String code;
        private String name;
        private Integer brandId;
        private String specifications;
        private String measurementUnit;
        private String packing;
        private String weight;
        private BigDecimal purchasePrice;
        private BigDecimal packingPrice;
        private BigDecimal materialPrice;
        private BigDecimal transportPrice;
        private String placeOfOrigin;
        private BigDecimal price;
        private BigDecimal tradePrice;
        private Integer stockLocation;
        private String mainImagePath;
        private Integer merchantId;
        private Integer reviewStatus;
        private Integer merchantType;
        private String dateManufacture;
        private Integer guaranteeDate;
        private String expirationDate;
        private String remarks;
        private String detailImagePath;
        private Integer accountId;
        private static final long serialVersionUID = 1L;

    public Integer getAccountId() {
        return accountId;
    }

    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    public String getDateManufacture() {
        return dateManufacture;
    }

    public void setDateManufacture(String dateManufacture) {
        this.dateManufacture = dateManufacture;
    }

    public String getExpirationDate() {
        return expirationDate;
    }

    public void setExpirationDate(String expirationDate) {
        this.expirationDate = expirationDate;
    }

    public Integer getId() {
            return id;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.id
         *
         * @param id the value for product.id
         *
         * @mbg.generated
         */
        public void setId(Integer id) {
            this.id = id;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.shelves_status
         *
         * @return the value of product.shelves_status
         *
         * @mbg.generated
         */
        public Integer getShelvesStatus() {
            return shelvesStatus;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.shelves_status
         *
         * @param shelvesStatus the value for product.shelves_status
         *
         * @mbg.generated
         */
        public void setShelvesStatus(Integer shelvesStatus) {
            this.shelvesStatus = shelvesStatus;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.offshelves_date
         *
         * @return the value of product.offshelves_date
         *
         * @mbg.generated
         */
        public Date getOffshelvesDate() {
            return offshelvesDate;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.offshelves_date
         *
         * @param offshelvesDate the value for product.offshelves_date
         *
         * @mbg.generated
         */
        public void setOffshelvesDate(Date offshelvesDate) {
            this.offshelvesDate = offshelvesDate;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.shelves_date
         *
         * @return the value of product.shelves_date
         *
         * @mbg.generated
         */
        public Date getShelvesDate() {
            return shelvesDate;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.shelves_date
         *
         * @param shelvesDate the value for product.shelves_date
         *
         * @mbg.generated
         */
        public void setShelvesDate(Date shelvesDate) {
            this.shelvesDate = shelvesDate;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.categoryone_id
         *
         * @return the value of product.categoryone_id
         *
         * @mbg.generated
         */
        public Integer getCategoryoneId() {
            return categoryoneId;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.categoryone_id
         *
         * @param categoryoneId the value for product.categoryone_id
         *
         * @mbg.generated
         */
        public void setCategoryoneId(Integer categoryoneId) {
            this.categoryoneId = categoryoneId;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.categorytwo_id
         *
         * @return the value of product.categorytwo_id
         *
         * @mbg.generated
         */
        public Integer getCategorytwoId() {
            return categorytwoId;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.categorytwo_id
         *
         * @param categorytwoId the value for product.categorytwo_id
         *
         * @mbg.generated
         */
        public void setCategorytwoId(Integer categorytwoId) {
            this.categorytwoId = categorytwoId;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.code
         *
         * @return the value of product.code
         *
         * @mbg.generated
         */
        public String getCode() {
            return code;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.code
         *
         * @param code the value for product.code
         *
         * @mbg.generated
         */
        public void setCode(String code) {
            this.code = code == null ? null : code.trim();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.name
         *
         * @return the value of product.name
         *
         * @mbg.generated
         */
        public String getName() {
            return name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.name
         *
         * @param name the value for product.name
         *
         * @mbg.generated
         */
        public void setName(String name) {
            this.name = name == null ? null : name.trim();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.brand_id
         *
         * @return the value of product.brand_id
         *
         * @mbg.generated
         */
        public Integer getBrandId() {
            return brandId;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.brand_id
         *
         * @param brandId the value for product.brand_id
         *
         * @mbg.generated
         */
        public void setBrandId(Integer brandId) {
            this.brandId = brandId;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.specifications
         *
         * @return the value of product.specifications
         *
         * @mbg.generated
         */
        public String getSpecifications() {
            return specifications;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.specifications
         *
         * @param specifications the value for product.specifications
         *
         * @mbg.generated
         */
        public void setSpecifications(String specifications) {
            this.specifications = specifications == null ? null : specifications.trim();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.measurement_unit
         *
         * @return the value of product.measurement_unit
         *
         * @mbg.generated
         */
        public String getMeasurementUnit() {
            return measurementUnit;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.measurement_unit
         *
         * @param measurementUnit the value for product.measurement_unit
         *
         * @mbg.generated
         */
        public void setMeasurementUnit(String measurementUnit) {
            this.measurementUnit = measurementUnit == null ? null : measurementUnit.trim();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.packing
         *
         * @return the value of product.packing
         *
         * @mbg.generated
         */
        public String getPacking() {
            return packing;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.packing
         *
         * @param packing the value for product.packing
         *
         * @mbg.generated
         */
        public void setPacking(String packing) {
            this.packing = packing == null ? null : packing.trim();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.weight
         *
         * @return the value of product.weight
         *
         * @mbg.generated
         */
        public String getWeight() {
            return weight;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.weight
         *
         * @param weight the value for product.weight
         *
         * @mbg.generated
         */
        public void setWeight(String weight) {
            this.weight = weight == null ? null : weight.trim();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.purchase_price
         *
         * @return the value of product.purchase_price
         *
         * @mbg.generated
         */
        public BigDecimal getPurchasePrice() {
            return purchasePrice;
        }
        public void setPurchasePrice(BigDecimal purchasePrice) {
            this.purchasePrice = purchasePrice;
        }
        public BigDecimal getPackingPrice() {
            return packingPrice;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.packing_price
         *
         * @param packingPrice the value for product.packing_price
         *
         * @mbg.generated
         */
        public void setPackingPrice(BigDecimal packingPrice) {
            this.packingPrice = packingPrice;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.material_price
         *
         * @return the value of product.material_price
         *
         * @mbg.generated
         */
        public BigDecimal getMaterialPrice() {
            return materialPrice;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.material_price
         *
         * @param materialPrice the value for product.material_price
         *
         * @mbg.generated
         */
        public void setMaterialPrice(BigDecimal materialPrice) {
            this.materialPrice = materialPrice;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.transport_price
         *
         * @return the value of product.transport_price
         *
         * @mbg.generated
         */
        public BigDecimal getTransportPrice() {
            return transportPrice;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.transport_price
         *
         * @param transportPrice the value for product.transport_price
         *
         * @mbg.generated
         */
        public void setTransportPrice(BigDecimal transportPrice) {
            this.transportPrice = transportPrice;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.place_of_origin
         *
         * @return the value of product.place_of_origin
         *
         * @mbg.generated
         */
        public String getPlaceOfOrigin() {
            return placeOfOrigin;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.place_of_origin
         *
         * @param placeOfOrigin the value for product.place_of_origin
         *
         * @mbg.generated
         */
        public void setPlaceOfOrigin(String placeOfOrigin) {
            this.placeOfOrigin = placeOfOrigin == null ? null : placeOfOrigin.trim();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.price
         *
         * @return the value of product.price
         *
         * @mbg.generated
         */
        public BigDecimal getPrice() {
            return price;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.price
         *
         * @param price the value for product.price
         *
         * @mbg.generated
         */
        public void setPrice(BigDecimal price) {
            this.price = price;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.trade_price
         *
         * @return the value of product.trade_price
         *
         * @mbg.generated
         */
        public BigDecimal getTradePrice() {
            return tradePrice;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.trade_price
         *
         * @param tradePrice the value for product.trade_price
         *
         * @mbg.generated
         */
        public void setTradePrice(BigDecimal tradePrice) {
            this.tradePrice = tradePrice;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.stock_location
         *
         * @return the value of product.stock_location
         *
         * @mbg.generated
         */
        public Integer getStockLocation() {
            return stockLocation;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.stock_location
         *
         * @param stockLocation the value for product.stock_location
         *
         * @mbg.generated
         */
        public void setStockLocation(Integer stockLocation) {
            this.stockLocation = stockLocation;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.main_image_path
         *
         * @return the value of product.main_image_path
         *
         * @mbg.generated
         */
        public String getMainImagePath() {
            return mainImagePath;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.main_image_path
         *
         * @param mainImagePath the value for product.main_image_path
         *
         * @mbg.generated
         */
        public void setMainImagePath(String mainImagePath) {
            this.mainImagePath = mainImagePath == null ? null : mainImagePath.trim();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.merchant_id
         *
         * @return the value of product.merchant_id
         *
         * @mbg.generated
         */
        public Integer getMerchantId() {
            return merchantId;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.merchant_id
         *
         * @param merchantId the value for product.merchant_id
         *
         * @mbg.generated
         */
        public void setMerchantId(Integer merchantId) {
            this.merchantId = merchantId;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.review_status
         *
         * @return the value of product.review_status
         *
         * @mbg.generated
         */
        public Integer getReviewStatus() {
            return reviewStatus;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.review_status
         *
         * @param reviewStatus the value for product.review_status
         *
         * @mbg.generated
         */
        public void setReviewStatus(Integer reviewStatus) {
            this.reviewStatus = reviewStatus;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.merchant_type
         *
         * @return the value of product.merchant_type
         *
         * @mbg.generated
         */
        public Integer getMerchantType() {
            return merchantType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.merchant_type
         *
         * @param merchantType the value for product.merchant_type
         *
         * @mbg.generated
         */
        public void setMerchantType(Integer merchantType) {
            this.merchantType = merchantType;
        }


        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.guarantee_date
         *
         * @return the value of product.guarantee_date
         *
         * @mbg.generated
         */
        public Integer getGuaranteeDate() {
            return guaranteeDate;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.guarantee_date
         *
         * @param guaranteeDate the value for product.guarantee_date
         *
         * @mbg.generated
         */
        public void setGuaranteeDate(Integer guaranteeDate) {
            this.guaranteeDate = guaranteeDate;
        }


        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.Remarks
         *
         * @return the value of product.Remarks
         *
         * @mbg.generated
         */
        public String getRemarks() {
            return remarks;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.Remarks
         *
         * @param remarks the value for product.Remarks
         *
         * @mbg.generated
         */
        public void setRemarks(String remarks) {
            this.remarks = remarks == null ? null : remarks.trim();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column product.detail_image_path
         *
         * @return the value of product.detail_image_path
         *
         * @mbg.generated
         */
        public String getDetailImagePath() {
            return detailImagePath;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column product.detail_image_path
         *
         * @param detailImagePath the value for product.detail_image_path
         *
         * @mbg.generated
         */
        public void setDetailImagePath(String detailImagePath) {
            this.detailImagePath = detailImagePath == null ? null : detailImagePath.trim();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table product
         *
         * @mbg.generated
         */
        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getClass().getSimpleName());
            sb.append(" [");
            sb.append("Hash = ").append(hashCode());
            sb.append(", id=").append(id);
            sb.append(", shelvesStatus=").append(shelvesStatus);
            sb.append(", offshelvesDate=").append(offshelvesDate);
            sb.append(", shelvesDate=").append(shelvesDate);
            sb.append(", categoryoneId=").append(categoryoneId);
            sb.append(", categorytwoId=").append(categorytwoId);
            sb.append(", code=").append(code);
            sb.append(", name=").append(name);
            sb.append(", brandId=").append(brandId);
            sb.append(", specifications=").append(specifications);
            sb.append(", measurementUnit=").append(measurementUnit);
            sb.append(", packing=").append(packing);
            sb.append(", weight=").append(weight);
            sb.append(", purchasePrice=").append(purchasePrice);
            sb.append(", packingPrice=").append(packingPrice);
            sb.append(", materialPrice=").append(materialPrice);
            sb.append(", transportPrice=").append(transportPrice);
            sb.append(", placeOfOrigin=").append(placeOfOrigin);
            sb.append(", price=").append(price);
            sb.append(", tradePrice=").append(tradePrice);
            sb.append(", stockLocation=").append(stockLocation);
            sb.append(", mainImagePath=").append(mainImagePath);
            sb.append(", merchantId=").append(merchantId);
            sb.append(", reviewStatus=").append(reviewStatus);
            sb.append(", merchantType=").append(merchantType);
            sb.append(", dateManufacture=").append(dateManufacture);
            sb.append(", guaranteeDate=").append(guaranteeDate);
            sb.append(", expirationDate=").append(expirationDate);
            sb.append(", remarks=").append(remarks);
            sb.append(", detailImagePath=").append(detailImagePath);
            sb.append(", serialVersionUID=").append(serialVersionUID);
            sb.append("]");
            return sb.toString();
        }
    }

