package com.kshl.huihuimall.base.dal.mapper;

import com.kshl.huihuimall.base.dal.entity.CategoryToBrand;
import com.kshl.huihuimall.base.dal.entity.CategoryToBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoryToBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_to_brand
     *
     * @mbg.generated
     */
    long countByExample(CategoryToBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_to_brand
     *
     * @mbg.generated
     */
    int deleteByExample(CategoryToBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_to_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_to_brand
     *
     * @mbg.generated
     */
    int insert(CategoryToBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_to_brand
     *
     * @mbg.generated
     */
    int insertSelective(CategoryToBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_to_brand
     *
     * @mbg.generated
     */
    List<CategoryToBrand> selectByExample(CategoryToBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_to_brand
     *
     * @mbg.generated
     */
    CategoryToBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_to_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CategoryToBrand record, @Param("example") CategoryToBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_to_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CategoryToBrand record, @Param("example") CategoryToBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_to_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CategoryToBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_to_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CategoryToBrand record);
}