package com.kshl.huihuimall.base.dal.mapper;

import com.kshl.huihuimall.base.dal.entity.FinancialConfigure;
import com.kshl.huihuimall.base.dal.entity.FinancialConfigureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FinancialConfigureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    long countByExample(FinancialConfigureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    int deleteByExample(FinancialConfigureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    int insert(FinancialConfigure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    int insertSelective(FinancialConfigure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    List<FinancialConfigure> selectByExample(FinancialConfigureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    FinancialConfigure selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FinancialConfigure record, @Param("example") FinancialConfigureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FinancialConfigure record, @Param("example") FinancialConfigureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FinancialConfigure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_configure
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FinancialConfigure record);
}