package com.kshl.huihuimall.base.dal.mapper;

import com.kshl.huihuimall.base.dal.entity.KsRoleToResource;
import com.kshl.huihuimall.base.dal.entity.KsRoleToResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KsRoleToResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role_to_resource
     *
     * @mbg.generated
     */
    long countByExample(KsRoleToResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role_to_resource
     *
     * @mbg.generated
     */
    int deleteByExample(KsRoleToResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role_to_resource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role_to_resource
     *
     * @mbg.generated
     */
    int insert(KsRoleToResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role_to_resource
     *
     * @mbg.generated
     */
    int insertSelective(KsRoleToResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role_to_resource
     *
     * @mbg.generated
     */
    List<KsRoleToResource> selectByExample(KsRoleToResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role_to_resource
     *
     * @mbg.generated
     */
    KsRoleToResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role_to_resource
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") KsRoleToResource record, @Param("example") KsRoleToResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role_to_resource
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") KsRoleToResource record, @Param("example") KsRoleToResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role_to_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KsRoleToResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ks_role_to_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KsRoleToResource record);
}