package com.kshl.huihuimall.base.dal.mapper;

import com.kshl.huihuimall.base.dal.entity.LivingPayBill;
import com.kshl.huihuimall.base.dal.entity.LivingPayBillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LivingPayBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table living_pay_bill
     *
     * @mbg.generated
     */
    long countByExample(LivingPayBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table living_pay_bill
     *
     * @mbg.generated
     */
    int deleteByExample(LivingPayBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table living_pay_bill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table living_pay_bill
     *
     * @mbg.generated
     */
    int insert(LivingPayBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table living_pay_bill
     *
     * @mbg.generated
     */
    int insertSelective(LivingPayBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table living_pay_bill
     *
     * @mbg.generated
     */
    List<LivingPayBill> selectByExample(LivingPayBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table living_pay_bill
     *
     * @mbg.generated
     */
    LivingPayBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table living_pay_bill
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LivingPayBill record, @Param("example") LivingPayBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table living_pay_bill
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LivingPayBill record, @Param("example") LivingPayBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table living_pay_bill
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LivingPayBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table living_pay_bill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LivingPayBill record);
}