package com.kshl.huihuimall.base.dal.mapper;

import com.kshl.huihuimall.base.dal.entity.LivingPay;
import com.kshl.huihuimall.base.dal.entity.LivingPayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LivingPayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table living_pay
     *
     * @mbg.generated
     */
    long countByExample(LivingPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table living_pay
     *
     * @mbg.generated
     */
    int deleteByExample(LivingPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table living_pay
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table living_pay
     *
     * @mbg.generated
     */
    int insert(LivingPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table living_pay
     *
     * @mbg.generated
     */
    int insertSelective(LivingPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table living_pay
     *
     * @mbg.generated
     */
    List<LivingPay> selectByExample(LivingPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table living_pay
     *
     * @mbg.generated
     */
    LivingPay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table living_pay
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LivingPay record, @Param("example") LivingPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table living_pay
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LivingPay record, @Param("example") LivingPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table living_pay
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LivingPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table living_pay
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LivingPay record);
}