package com.kshl.huihuimall.base.dal.mapper;

import com.kshl.huihuimall.base.dal.entity.ThiradAccountType;
import com.kshl.huihuimall.base.dal.entity.ThiradAccountTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ThiradAccountTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    long countByExample(ThiradAccountTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    int deleteByExample(ThiradAccountTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    int insert(ThiradAccountType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    int insertSelective(ThiradAccountType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    List<ThiradAccountType> selectByExample(ThiradAccountTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    ThiradAccountType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ThiradAccountType record, @Param("example") ThiradAccountTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ThiradAccountType record, @Param("example") ThiradAccountTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ThiradAccountType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirad_account_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ThiradAccountType record);
}